name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK and Android
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          sdk-platform: "android-34"

      - name: Build and Run Tests
        run: |
          ./gradlew build
          ./gradlew test
          ./gradlew spotlessCheck
          ./gradlew spotlessApply

      - name: Upload Test Results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: app/build/test-results

      - name: Set Status - Success
        if: ${{ failure() == false }}
        uses: softprops/action-gh-release@v1
        with:
          files: /dev/null
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Status - Failure
        if: ${{ failure() == true }}
        uses: softprops/action-gh-release@v1
        with:
          files: /dev/null
          tag_name: failure
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
