name: CI

on:
  pull_request:
    branches:
      - 'main'
      - '*' # Exécutez uniquement pour les pull requests

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK and Android
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          sdk-platform: "android-34"

      - name: Build and Run Tests
        run: |
          ./gradlew build
          ./gradlew test
          ./gradlew spotlessCheck
          ./gradlew spotlessApply

      - name: Upload Test Results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: app/build/test-results

      - name: Comment on PR
        if: failure() # Exécuter seulement en cas d'erreur
        run: |
          echo "The CI workflow has completed. Status: ${{ job.status }}"
          echo "::set-output name=comment::The CI workflow has completed. Status: ${{ job.status }}"
        id: comment

      - name: Comment on PR (GitHub Script)
        if: failure() # Exécuter seulement en cas d'erreur
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const comment = process.env.comment;
            const { context, getOctokit } = require('@actions/github');

            const octokit = new getOctokit(process.env.GITHUB_TOKEN);

            octokit.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: comment,
            });
